### ISSUE TITLE
Standard FD55B drive?

### ISSUE THREAD

**Issue by ulihuber** [eedede/treckr#1]
I kept my old Apple II disks but not the old drives.
Now I got an original TEAC FD55B for cheap and wonder if it could be possible to use it for this project. While the 34 pin interface is of course different, with SW-modification the phase signals could easily  be changed to step/dir. But what about tho other signals? I remember there were some small modifications to adapt a TEAC oder BASF floppy drive to an Apple II but I cant' remember those. Any idea?

**Comment by eedede** [comment]
@ulihuber : Missed any notification, sorry. I did not use FD55B so I cannot give any useful practical advice. 

There are some infos here: https://retrocomputing.stackexchange.com/questions/16122/i-need-to-find-a-controller-card-for-an-apple-ii-5-25-inch-floppy-drive-the-20
which points to some documentation for the erphi disc controller: https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Interface%20Cards/Disk%20Drive%20Controllers/erphi%20Disk%20Controller/Manuals/

Hope that helps. Good look for your project!
